// Loads the ingested catalog. courses.json is generated by `npm run ingest`.
// If it's missing we boot with an empty catalog and warn — keeps dev
// environments from hard-failing on a fresh clone.

import * as fs from "fs";
import * as path from "path";
import type { Course } from "../models/Course";

const COURSES_JSON = path.resolve(__dirname, "../../data/courses.json");

function loadCourses(): Course[] {
    if (!fs.existsSync(COURSES_JSON)) {
        console.warn(
            `[courses] ${COURSES_JSON} missing. Run \`npm run ingest\` to populate it.`,
        );
        return [];
    }
    return JSON.parse(fs.readFileSync(COURSES_JSON, "utf8")) as Course[];
}

export const courses: Course[] = loadCourses();
